default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: atm-dev

test:
  <<: *default
  database: atm-test

production:
  <<: *default
  database: atm
